Fix Markov Control Mode
AlgorithmsTheory/lms-core pull request #68
Opened 2020-10-02 12:15 UTC by nice-your-code

Ошибка похожая на:
https://github.com/AlgorithmsTheory/lms-core/pull/67
Символ '^' теперь нормально перерабатывается
Также убрал логирование, чтобы не засорять лог

2020-10-02 12:20 UTC, SorokinStanislav requested changes

2020-10-02 12:20 UTC, SorokinStanislav commented on app/Http/Controllers/Emulators/EmulatorController.php
> +        //Log::info('Checking');
не нужно оставлять код закомментированным.
В данном случае, чтобы не засорять лог, можно понизить уровень логирования до debug

2020-10-05 18:09 UTC, nice-your-code commented on app/Http/Controllers/Emulators/EmulatorController.php
> +        //Log::info('Checking');
Понизил до debug

2020-10-05 18:27 UTC, SorokinStanislav approved these changes

2020-10-05 18:27 UTC, merged