Feature turing control mode
AlgorithmsTheory/lms-core pull request #80
Opened 2022-01-16 16:04 UTC by Personioto

2022-02-03 15:01 UTC, SorokinStanislav requested changes

2022-02-03 15:01 UTC, SorokinStanislav commented on app/Http/Controllers/TestController.php
> +        $groupInfo = Group::where('group_id', '=', $user_data['group'])->first();
кажется, что можно получить одним запросом в базу через join

2022-02-09 06:46 UTC, Personioto commented on app/Http/Controllers/TestController.php
> +        /*
верно, убрал

2022-02-09 06:46 UTC, Personioto commented on app/Http/Controllers/TestController.php
> +    public function controlTests2() {
controlTests2 - это старый метод, убрал. Новый controlTests

2022-02-09 06:47 UTC, Personioto commented on database/migrations/2021_11_05_154148_add_deleted_at_to_users_table.php
> +            // ��� ������ ������� ������� deleted_at � ������� users,
исправил win-1251 на utf-8

2022-02-09 06:47 UTC, Personioto commented on app/Http/Controllers/PersonalAccount.php
> +            #$user = User::whereId($res->id)->join('groups', 'groups.group_id', '=', 'users.group')->get();
убрал

2022-02-09 06:47 UTC, Personioto commented on app/Http/Controllers/TestController.php
> +        $groupInfo = Group::where('group_id', '=', $user_data['group'])->first();
не актуально, т.к. метод удалён, нигде теперь не используется

2022-02-09 10:31 UTC, SorokinStanislav approved these changes

2022-02-09 11:11 UTC, merged